from tuya_device_handlers import TUYA_QUIRKS_REGISTRY
from tuya_device_handlers.builder import DeviceQuirk
from tuya_device_handlers.const import DPMode

(
    DeviceQuirk()
    .applies_to(product_id="layxxij0sdbrfmrf")
    .add_dpid_integer(
        dpid=8,
        dpcode="temp_current",
        dpmode=DPMode.READ,
        unit="°C",
        min=0,
        max=1000,
        scale=1,
        step=1,
    )
    .add_dpid_integer(
        dpid=106,
        dpcode="ph_current",
        dpmode=DPMode.READ,
        unit="pH",
        min=0,
        max=1400,
        scale=2,
        step=1,
    )
    .add_dpid_integer(
        dpid=111,
        dpcode="tds_current",
        dpmode=DPMode.READ,
        unit="ppm",
        min=0,
        max=50000,
        scale=0,
        step=1,
    )
    .add_dpid_integer(
        dpid=116,
        dpcode="ec_current",
        dpmode=DPMode.READ,
        unit="µS/cm",
        min=0,
        max=20000,
        scale=2,
        step=1,
    )
    .add_dpid_integer(
        dpid=121,
        dpcode="salinity_current",
        dpmode=DPMode.READ,
        unit="ppt",
        min=0,
        max=10000,
        scale=1,
        step=1,
    )
    .add_dpid_integer(
        dpid=126,
        dpcode="pro_current",
        dpmode=DPMode.READ,
        unit="",
        min=0,
        max=2000,
        scale=0,
        step=1,
    )
    .add_dpid_integer(
        dpid=131,
        dpcode="orp_current",
        dpmode=DPMode.READ,
        unit="mV",
        min=0,
        max=2000,
        scale=0,
        step=1,
    )
    .add_dpid_integer(
        dpid=136,
        dpcode="cf_current",
        dpmode=DPMode.READ,
        unit="µS/cm",
        min=0,
        max=20000,
        scale=0,
        step=1,
    )
    .add_dpid_integer(
        dpid=141,
        dpcode="rh_current",
        dpmode=DPMode.READ,
        unit="%",
        min=0,
        max=100,
        scale=0,
        step=1,
    )
    .register(TUYA_QUIRKS_REGISTRY)
)
