"""Helpers for quirk sensor tests.

The category mapping below mirrors the ``SENSORS`` dictionary in Home
Assistant core, so tests can assert that a quirk produces the sensors core
would build for a device.
https://github.com/home-assistant/core/blob/dev/homeassistant/components/tuya/sensor.py
"""

from dataclasses import dataclass

from tuya_sharing import CustomerDevice

from tuya_device_handlers.definition.sensor import (
    SensorDefinition,
    get_default_definition,
)
from tuya_device_handlers.device_wrapper.common import (
    DPCodeTypeInformationWrapper,
    DPCodeWrapper,
)
from tuya_device_handlers.device_wrapper.sensor import (
    ElectricityCurrentJsonWrapper,
    ElectricityCurrentRawWrapper,
    ElectricityPowerJsonWrapper,
    ElectricityPowerRawWrapper,
    ElectricityVoltageJsonWrapper,
    ElectricityVoltageRawWrapper,
    WindDirectionEnumWrapper,
)

_WrapperClasses = tuple[type[DPCodeTypeInformationWrapper], ...]

# Wrapper tuples for RAW/JSON electricity DPs, mirroring Home Assistant core.
_CURRENT_WRAPPER = (ElectricityCurrentRawWrapper, ElectricityCurrentJsonWrapper)
_POWER_WRAPPER = (ElectricityPowerRawWrapper, ElectricityPowerJsonWrapper)
_VOLTAGE_WRAPPER = (ElectricityVoltageRawWrapper, ElectricityVoltageJsonWrapper)
_WIND_DIRECTION_WRAPPER = (WindDirectionEnumWrapper,)


@dataclass(frozen=True)
class SensorEntityDescription:
    """Describes a Tuya sensor, mirroring the Home Assistant core mapping."""

    dpcode: str
    wrapper_class: _WrapperClasses | None = None


_SENSORS: dict[str, tuple[SensorEntityDescription, ...]] = {
    "aqcz": (
        SensorEntityDescription("cur_current"),
        SensorEntityDescription("cur_power"),
        SensorEntityDescription("cur_voltage"),
    ),
    "bh": (
        SensorEntityDescription("temp_current"),
        SensorEntityDescription("temp_current_f"),
        SensorEntityDescription("status"),
    ),
    "cl": (SensorEntityDescription("time_total"),),
    "co2bj": (
        SensorEntityDescription("humidity_value"),
        SensorEntityDescription("temp_current"),
        SensorEntityDescription("co2_value"),
        SensorEntityDescription("ch2o_value"),
        SensorEntityDescription("voc_value"),
        SensorEntityDescription("pm25_value"),
        SensorEntityDescription("pm10"),
        SensorEntityDescription("battery_percentage"),
        SensorEntityDescription("battery"),
        SensorEntityDescription("battery_state"),
        SensorEntityDescription("battery_value"),
        SensorEntityDescription("va_battery"),
    ),
    "cobj": (
        SensorEntityDescription("co_value"),
        SensorEntityDescription("battery_percentage"),
        SensorEntityDescription("battery"),
        SensorEntityDescription("battery_state"),
        SensorEntityDescription("battery_value"),
        SensorEntityDescription("va_battery"),
    ),
    "cs": (
        SensorEntityDescription("temp_indoor"),
        SensorEntityDescription("humidity_indoor"),
    ),
    "cwjwq": (
        SensorEntityDescription("work_state_e"),
        SensorEntityDescription("battery_percentage"),
        SensorEntityDescription("battery"),
        SensorEntityDescription("battery_state"),
        SensorEntityDescription("battery_value"),
        SensorEntityDescription("va_battery"),
    ),
    "cwwsq": (
        SensorEntityDescription("battery_percentage"),
        SensorEntityDescription("battery"),
        SensorEntityDescription("battery_state"),
        SensorEntityDescription("battery_value"),
        SensorEntityDescription("va_battery"),
        SensorEntityDescription("feed_report"),
    ),
    "cwysj": (
        SensorEntityDescription("uv_runtime"),
        SensorEntityDescription("pump_time"),
        SensorEntityDescription("filter_life"),
        SensorEntityDescription("water_time"),
        SensorEntityDescription("water_level"),
    ),
    "cz": (
        SensorEntityDescription("cur_current"),
        SensorEntityDescription("cur_power"),
        SensorEntityDescription("cur_voltage"),
        SensorEntityDescription("add_ele"),
        SensorEntityDescription("pro_add_ele"),
    ),
    "dghsxj": (
        SensorEntityDescription("sensor_temperature"),
        SensorEntityDescription("sensor_humidity"),
        SensorEntityDescription("wireless_electricity"),
    ),
    "dgnbj": (
        SensorEntityDescription("gas_sensor_value"),
        SensorEntityDescription("ch4_sensor_value"),
        SensorEntityDescription("voc_value"),
        SensorEntityDescription("pm25_value"),
        SensorEntityDescription("co_value"),
        SensorEntityDescription("co2_value"),
        SensorEntityDescription("ec_current"),
        SensorEntityDescription("ch2o_value"),
        SensorEntityDescription("bright_state"),
        SensorEntityDescription("bright_value"),
        SensorEntityDescription("temp_current"),
        SensorEntityDescription("humidity_value"),
        SensorEntityDescription("orp_current"),
        SensorEntityDescription("ph_current"),
        SensorEntityDescription("smoke_sensor_value"),
        SensorEntityDescription("battery_percentage"),
        SensorEntityDescription("battery"),
        SensorEntityDescription("battery_state"),
        SensorEntityDescription("battery_value"),
        SensorEntityDescription("va_battery"),
    ),
    "dlq": (
        SensorEntityDescription("total_forward_energy"),
        SensorEntityDescription("add_ele"),
        SensorEntityDescription("forward_energy_total"),
        SensorEntityDescription("reverse_energy_total"),
        SensorEntityDescription("cur_neutral"),
        SensorEntityDescription("supply_frequency"),
        SensorEntityDescription("phase_a", _CURRENT_WRAPPER),
        SensorEntityDescription("phase_a", _POWER_WRAPPER),
        SensorEntityDescription("phase_a", _VOLTAGE_WRAPPER),
        SensorEntityDescription("phase_b", _CURRENT_WRAPPER),
        SensorEntityDescription("phase_b", _POWER_WRAPPER),
        SensorEntityDescription("phase_b", _VOLTAGE_WRAPPER),
        SensorEntityDescription("phase_c", _CURRENT_WRAPPER),
        SensorEntityDescription("phase_c", _POWER_WRAPPER),
        SensorEntityDescription("phase_c", _VOLTAGE_WRAPPER),
        SensorEntityDescription("cur_current"),
        SensorEntityDescription("cur_power"),
        SensorEntityDescription("cur_voltage"),
    ),
    "fs": (SensorEntityDescription("temp_current"),),
    "ggq": (
        SensorEntityDescription("battery_percentage"),
        SensorEntityDescription("battery"),
        SensorEntityDescription("battery_state"),
        SensorEntityDescription("battery_value"),
        SensorEntityDescription("va_battery"),
    ),
    "hjjcy": (
        SensorEntityDescription("air_quality_index"),
        SensorEntityDescription("temp_current"),
        SensorEntityDescription("humidity_value"),
        SensorEntityDescription("co2_value"),
        SensorEntityDescription("ch2o_value"),
        SensorEntityDescription("voc_value"),
        SensorEntityDescription("pm25_value"),
        SensorEntityDescription("pm10"),
        SensorEntityDescription("battery_percentage"),
        SensorEntityDescription("battery"),
        SensorEntityDescription("battery_state"),
        SensorEntityDescription("battery_value"),
        SensorEntityDescription("va_battery"),
    ),
    "jqbj": (
        SensorEntityDescription("co2_value"),
        SensorEntityDescription("voc_value"),
        SensorEntityDescription("pm25_value"),
        SensorEntityDescription("va_humidity"),
        SensorEntityDescription("va_temperature"),
        SensorEntityDescription("ch2o_value"),
        SensorEntityDescription("battery_percentage"),
        SensorEntityDescription("battery"),
        SensorEntityDescription("battery_state"),
        SensorEntityDescription("battery_value"),
        SensorEntityDescription("va_battery"),
    ),
    "jsq": (
        SensorEntityDescription("humidity_current"),
        SensorEntityDescription("temp_current"),
        SensorEntityDescription("temp_current_f"),
        SensorEntityDescription("level_current"),
    ),
    "jwbj": (
        SensorEntityDescription("ch4_sensor_value"),
        SensorEntityDescription("battery_percentage"),
        SensorEntityDescription("battery"),
        SensorEntityDescription("battery_state"),
        SensorEntityDescription("battery_value"),
        SensorEntityDescription("va_battery"),
    ),
    "kg": (
        SensorEntityDescription("cur_current"),
        SensorEntityDescription("cur_power"),
        SensorEntityDescription("cur_voltage"),
        SensorEntityDescription("add_ele"),
        SensorEntityDescription("pro_add_ele"),
    ),
    "kj": (
        SensorEntityDescription("filter"),
        SensorEntityDescription("pm25"),
        SensorEntityDescription("temp"),
        SensorEntityDescription("humidity"),
        SensorEntityDescription("tvoc"),
        SensorEntityDescription("eco2"),
        SensorEntityDescription("total_time"),
        SensorEntityDescription("total_pm"),
        SensorEntityDescription("air_quality"),
    ),
    "ldcg": (
        SensorEntityDescription("bright_state"),
        SensorEntityDescription("bright_value"),
        SensorEntityDescription("temp_current"),
        SensorEntityDescription("humidity_value"),
        SensorEntityDescription("co2_value"),
        SensorEntityDescription("battery_percentage"),
        SensorEntityDescription("battery"),
        SensorEntityDescription("battery_state"),
        SensorEntityDescription("battery_value"),
        SensorEntityDescription("va_battery"),
    ),
    "mc": (
        SensorEntityDescription("battery_percentage"),
        SensorEntityDescription("battery"),
        SensorEntityDescription("battery_state"),
        SensorEntityDescription("battery_value"),
        SensorEntityDescription("va_battery"),
    ),
    "mcs": (
        SensorEntityDescription("battery_percentage"),
        SensorEntityDescription("battery"),
        SensorEntityDescription("battery_state"),
        SensorEntityDescription("battery_value"),
        SensorEntityDescription("va_battery"),
    ),
    "msp": (
        SensorEntityDescription("cat_weight"),
        SensorEntityDescription("excretion_time_day"),
        SensorEntityDescription("excretion_times_day"),
        SensorEntityDescription("status"),
    ),
    "mzj": (
        SensorEntityDescription("temp_current"),
        SensorEntityDescription("status"),
        SensorEntityDescription("remain_time"),
    ),
    "pc": (
        SensorEntityDescription("cur_current"),
        SensorEntityDescription("cur_power"),
        SensorEntityDescription("cur_voltage"),
        SensorEntityDescription("add_ele"),
        SensorEntityDescription("pro_add_ele"),
    ),
    "pir": (
        SensorEntityDescription("battery_percentage"),
        SensorEntityDescription("battery"),
        SensorEntityDescription("battery_state"),
        SensorEntityDescription("battery_value"),
        SensorEntityDescription("va_battery"),
    ),
    "pm2.5": (
        SensorEntityDescription("pm25_value"),
        SensorEntityDescription("ch2o_value"),
        SensorEntityDescription("voc_value"),
        SensorEntityDescription("temp_current"),
        SensorEntityDescription("co2_value"),
        SensorEntityDescription("humidity_value"),
        SensorEntityDescription("pm1"),
        SensorEntityDescription("pm10"),
        SensorEntityDescription("battery_percentage"),
        SensorEntityDescription("battery"),
        SensorEntityDescription("battery_state"),
        SensorEntityDescription("battery_value"),
        SensorEntityDescription("va_battery"),
    ),
    "qn": (SensorEntityDescription("work_power"),),
    "qxj": (
        SensorEntityDescription("va_temperature"),
        SensorEntityDescription("temp_current"),
        SensorEntityDescription("temp_current_external"),
        SensorEntityDescription("temp_current_external_1"),
        SensorEntityDescription("temp_current_external_2"),
        SensorEntityDescription("temp_current_external_3"),
        SensorEntityDescription("va_humidity"),
        SensorEntityDescription("humidity_value"),
        SensorEntityDescription("humidity_outdoor"),
        SensorEntityDescription("humidity_outdoor_1"),
        SensorEntityDescription("humidity_outdoor_2"),
        SensorEntityDescription("humidity_outdoor_3"),
        SensorEntityDescription("atmospheric_pressture"),
        SensorEntityDescription("bright_value"),
        SensorEntityDescription("windspeed_avg"),
        SensorEntityDescription("rain_24h"),
        SensorEntityDescription("rain_rate"),
        SensorEntityDescription("uv_index"),
        SensorEntityDescription("wind_direct", _WIND_DIRECTION_WRAPPER),
        SensorEntityDescription("dew_point_temp"),
        SensorEntityDescription("feellike_temp"),
        SensorEntityDescription("heat_index"),
        SensorEntityDescription("windchill_index"),
        SensorEntityDescription("battery_percentage"),
        SensorEntityDescription("battery"),
        SensorEntityDescription("battery_state"),
        SensorEntityDescription("battery_value"),
        SensorEntityDescription("va_battery"),
    ),
    "rqbj": (
        SensorEntityDescription("gas_sensor_value"),
        SensorEntityDescription("battery_percentage"),
        SensorEntityDescription("battery"),
        SensorEntityDescription("battery_state"),
        SensorEntityDescription("battery_value"),
        SensorEntityDescription("va_battery"),
    ),
    "sd": (
        SensorEntityDescription("clean_area"),
        SensorEntityDescription("clean_time"),
        SensorEntityDescription("total_clean_area"),
        SensorEntityDescription("total_clean_time"),
        SensorEntityDescription("total_clean_count"),
        SensorEntityDescription("duster_cloth"),
        SensorEntityDescription("edge_brush"),
        SensorEntityDescription("filter"),
        SensorEntityDescription("roll_brush"),
        SensorEntityDescription("electricity_left"),
    ),
    "sfkzq": (
        SensorEntityDescription("time_use"),
        SensorEntityDescription("use_time_one"),
        SensorEntityDescription("work_state"),
        SensorEntityDescription("battery_percentage"),
        SensorEntityDescription("battery"),
        SensorEntityDescription("battery_state"),
        SensorEntityDescription("battery_value"),
        SensorEntityDescription("va_battery"),
    ),
    "sgbj": (
        SensorEntityDescription("battery_percentage"),
        SensorEntityDescription("battery"),
        SensorEntityDescription("battery_state"),
        SensorEntityDescription("battery_value"),
        SensorEntityDescription("va_battery"),
    ),
    "sj": (
        SensorEntityDescription("battery_percentage"),
        SensorEntityDescription("battery"),
        SensorEntityDescription("battery_state"),
        SensorEntityDescription("battery_value"),
        SensorEntityDescription("va_battery"),
    ),
    "sos": (
        SensorEntityDescription("battery_percentage"),
        SensorEntityDescription("battery"),
        SensorEntityDescription("battery_state"),
        SensorEntityDescription("battery_value"),
        SensorEntityDescription("va_battery"),
    ),
    "sp": (
        SensorEntityDescription("sensor_temperature"),
        SensorEntityDescription("sensor_humidity"),
        SensorEntityDescription("wireless_electricity"),
    ),
    "swtz": (
        SensorEntityDescription("temp_current"),
        SensorEntityDescription("temp_current_2"),
        SensorEntityDescription("battery_percentage"),
        SensorEntityDescription("battery"),
        SensorEntityDescription("battery_state"),
        SensorEntityDescription("battery_value"),
        SensorEntityDescription("va_battery"),
    ),
    "sz": (
        SensorEntityDescription("temp_current"),
        SensorEntityDescription("humidity_current"),
    ),
    "szjcy": (
        SensorEntityDescription("tds_in"),
        SensorEntityDescription("temp_current"),
        SensorEntityDescription("battery_percentage"),
        SensorEntityDescription("battery"),
        SensorEntityDescription("battery_state"),
        SensorEntityDescription("battery_value"),
        SensorEntityDescription("va_battery"),
    ),
    "szjqr": (
        SensorEntityDescription("battery_percentage"),
        SensorEntityDescription("battery"),
        SensorEntityDescription("battery_state"),
        SensorEntityDescription("battery_value"),
        SensorEntityDescription("va_battery"),
    ),
    "tdq": (
        SensorEntityDescription("cur_current"),
        SensorEntityDescription("cur_power"),
        SensorEntityDescription("cur_voltage"),
        SensorEntityDescription("add_ele"),
        SensorEntityDescription("va_temperature"),
        SensorEntityDescription("temp_current"),
        SensorEntityDescription("va_humidity"),
        SensorEntityDescription("humidity_value"),
        SensorEntityDescription("bright_value"),
        SensorEntityDescription("battery_percentage"),
        SensorEntityDescription("battery"),
        SensorEntityDescription("battery_state"),
        SensorEntityDescription("battery_value"),
        SensorEntityDescription("va_battery"),
    ),
    "tyndj": (
        SensorEntityDescription("battery_percentage"),
        SensorEntityDescription("battery"),
        SensorEntityDescription("battery_state"),
        SensorEntityDescription("battery_value"),
        SensorEntityDescription("va_battery"),
    ),
    "voc": (
        SensorEntityDescription("co2_value"),
        SensorEntityDescription("pm25_value"),
        SensorEntityDescription("ch2o_value"),
        SensorEntityDescription("humidity_value"),
        SensorEntityDescription("temp_current"),
        SensorEntityDescription("voc_value"),
        SensorEntityDescription("battery_percentage"),
        SensorEntityDescription("battery"),
        SensorEntityDescription("battery_state"),
        SensorEntityDescription("battery_value"),
        SensorEntityDescription("va_battery"),
    ),
    "wg2": (
        SensorEntityDescription("battery_percentage"),
        SensorEntityDescription("battery"),
        SensorEntityDescription("battery_state"),
        SensorEntityDescription("battery_value"),
        SensorEntityDescription("va_battery"),
    ),
    "wk": (
        SensorEntityDescription("battery_percentage"),
        SensorEntityDescription("battery"),
        SensorEntityDescription("battery_state"),
        SensorEntityDescription("battery_value"),
        SensorEntityDescription("va_battery"),
    ),
    "wkcz": (
        SensorEntityDescription("humidity_value"),
        SensorEntityDescription("temp_current"),
        SensorEntityDescription("cur_current"),
        SensorEntityDescription("cur_power"),
        SensorEntityDescription("cur_voltage"),
    ),
    "wkf": (
        SensorEntityDescription("battery_percentage"),
        SensorEntityDescription("battery"),
        SensorEntityDescription("battery_state"),
        SensorEntityDescription("battery_value"),
        SensorEntityDescription("va_battery"),
    ),
    "wnykq": (
        SensorEntityDescription("va_temperature"),
        SensorEntityDescription("va_humidity"),
        SensorEntityDescription("cur_current"),
        SensorEntityDescription("cur_power"),
        SensorEntityDescription("cur_voltage"),
    ),
    "wsdcg": (
        SensorEntityDescription("va_temperature"),
        SensorEntityDescription("temp_current"),
        SensorEntityDescription("va_humidity"),
        SensorEntityDescription("humidity_value"),
        SensorEntityDescription("bright_value"),
        SensorEntityDescription("battery_percentage"),
        SensorEntityDescription("battery"),
        SensorEntityDescription("battery_state"),
        SensorEntityDescription("battery_value"),
        SensorEntityDescription("va_battery"),
    ),
    "wxkg": (
        SensorEntityDescription("battery_percentage"),
        SensorEntityDescription("battery"),
        SensorEntityDescription("battery_state"),
        SensorEntityDescription("battery_value"),
        SensorEntityDescription("va_battery"),
    ),
    "xnyjcn": (
        SensorEntityDescription("current_soc"),
        SensorEntityDescription("pv_power_total"),
        SensorEntityDescription("pv_power_channel_1"),
        SensorEntityDescription("pv_power_channel_2"),
        SensorEntityDescription("battery_power"),
        SensorEntityDescription("inverter_output_power"),
        SensorEntityDescription("cumulative_energy_generated_pv"),
        SensorEntityDescription("cumulative_energy_output_inv"),
        SensorEntityDescription("cumulative_energy_discharged"),
        SensorEntityDescription("cumulative_energy_charged"),
        SensorEntityDescription("cuml_e_export_offgrid1"),
    ),
    "ylcg": (
        SensorEntityDescription("pressure_value"),
        SensorEntityDescription("battery_percentage"),
        SensorEntityDescription("battery"),
        SensorEntityDescription("battery_state"),
        SensorEntityDescription("battery_value"),
        SensorEntityDescription("va_battery"),
    ),
    "ywbj": (
        SensorEntityDescription("smoke_sensor_value"),
        SensorEntityDescription("battery_percentage"),
        SensorEntityDescription("battery"),
        SensorEntityDescription("battery_state"),
        SensorEntityDescription("battery_value"),
        SensorEntityDescription("va_battery"),
    ),
    "ywcgq": (
        SensorEntityDescription("liquid_state"),
        SensorEntityDescription("liquid_depth"),
        SensorEntityDescription("liquid_level_percent"),
    ),
    "zd": (
        SensorEntityDescription("battery_percentage"),
        SensorEntityDescription("battery"),
        SensorEntityDescription("battery_state"),
        SensorEntityDescription("battery_value"),
        SensorEntityDescription("va_battery"),
    ),
    "zndb": (
        SensorEntityDescription("forward_energy_total"),
        SensorEntityDescription("reverse_energy_total"),
        SensorEntityDescription("power_total"),
        SensorEntityDescription("total_power"),
        SensorEntityDescription("supply_frequency"),
        SensorEntityDescription("phase_a", _CURRENT_WRAPPER),
        SensorEntityDescription("phase_a", _POWER_WRAPPER),
        SensorEntityDescription("phase_a", _VOLTAGE_WRAPPER),
        SensorEntityDescription("phase_b", _CURRENT_WRAPPER),
        SensorEntityDescription("phase_b", _POWER_WRAPPER),
        SensorEntityDescription("phase_b", _VOLTAGE_WRAPPER),
        SensorEntityDescription("phase_c", _CURRENT_WRAPPER),
        SensorEntityDescription("phase_c", _POWER_WRAPPER),
        SensorEntityDescription("phase_c", _VOLTAGE_WRAPPER),
    ),
    "znnbq": (
        SensorEntityDescription("reverse_energy_total"),
        SensorEntityDescription("power_total"),
        SensorEntityDescription("temp_current"),
    ),
    "znrb": (
        SensorEntityDescription("compressor_strength"),
        SensorEntityDescription("temp_around"),
        SensorEntityDescription("temp_coiler"),
        SensorEntityDescription("temp_current"),
        SensorEntityDescription("temp_effluent"),
        SensorEntityDescription("temp_venting"),
    ),
    "zwjcy": (
        SensorEntityDescription("temp_current"),
        SensorEntityDescription("humidity"),
        SensorEntityDescription("battery_percentage"),
        SensorEntityDescription("battery"),
        SensorEntityDescription("battery_state"),
        SensorEntityDescription("battery_value"),
        SensorEntityDescription("va_battery"),
    ),
}


def get_sensor_default_definitions(
    device: CustomerDevice,
) -> list[SensorDefinition]:
    """Get the default sensor definitions Home Assistant builds for a device."""
    values = [
        get_default_definition(
            device, description.dpcode, description.wrapper_class
        )
        for description in _SENSORS.get(device.category, ())
    ]
    return [definition for definition in values if definition]


def get_sensor_wrapper(
    definitions: list[SensorDefinition], dpcode: str
) -> DPCodeWrapper | None:
    """Extract the sensor wrapper for a DPCode from a list of definitions."""
    for definition in definitions:
        wrapper = definition.sensor_wrapper
        if isinstance(wrapper, DPCodeWrapper) and wrapper.dpcode == dpcode:
            return wrapper
    return None
