"""Helpers for quirk sensor tests.

The category-to-DPCode mapping below mirrors the ``SENSORS`` dictionary in
Home Assistant core, so tests can assert that a quirk produces the sensors
core would build for a device.
https://github.com/home-assistant/core/blob/dev/homeassistant/components/tuya/sensor.py
"""

from tuya_sharing import CustomerDevice

from tuya_device_handlers.definition.sensor import (
    SensorDefinition,
    get_default_definition,
)
from tuya_device_handlers.device_wrapper.common import (
    DPCodeTypeInformationWrapper,
    DPCodeWrapper,
)
from tuya_device_handlers.device_wrapper.sensor import (
    ElectricityCurrentJsonWrapper,
    ElectricityCurrentRawWrapper,
    ElectricityPowerJsonWrapper,
    ElectricityPowerRawWrapper,
    ElectricityVoltageJsonWrapper,
    ElectricityVoltageRawWrapper,
    WindDirectionEnumWrapper,
)

# Wrapper tuples for RAW/JSON electricity DPs, mirroring Home Assistant core.
_CURRENT_WRAPPER = (ElectricityCurrentRawWrapper, ElectricityCurrentJsonWrapper)
_POWER_WRAPPER = (ElectricityPowerRawWrapper, ElectricityPowerJsonWrapper)
_VOLTAGE_WRAPPER = (ElectricityVoltageRawWrapper, ElectricityVoltageJsonWrapper)
_WIND_DIRECTION_WRAPPER = (WindDirectionEnumWrapper,)

_WrapperClasses = tuple[type[DPCodeTypeInformationWrapper], ...]
# A sensor entry is a DPCode, optionally paired with the wrapper classes
# Home Assistant core uses to decode it.
_SensorEntry = str | tuple[str, _WrapperClasses]

_SENSOR_DPCODES: dict[str, tuple[_SensorEntry, ...]] = {
    "aqcz": (
        "cur_current",
        "cur_power",
        "cur_voltage",
    ),
    "bh": (
        "temp_current",
        "temp_current_f",
        "status",
    ),
    "cl": ("time_total",),
    "co2bj": (
        "humidity_value",
        "temp_current",
        "co2_value",
        "ch2o_value",
        "voc_value",
        "pm25_value",
        "pm10",
        "battery_percentage",
        "battery",
        "battery_state",
        "battery_value",
        "va_battery",
    ),
    "cobj": (
        "co_value",
        "battery_percentage",
        "battery",
        "battery_state",
        "battery_value",
        "va_battery",
    ),
    "cs": (
        "temp_indoor",
        "humidity_indoor",
    ),
    "cwjwq": (
        "work_state_e",
        "battery_percentage",
        "battery",
        "battery_state",
        "battery_value",
        "va_battery",
    ),
    "cwwsq": (
        "battery_percentage",
        "battery",
        "battery_state",
        "battery_value",
        "va_battery",
        "feed_report",
    ),
    "cwysj": (
        "uv_runtime",
        "pump_time",
        "filter_life",
        "water_time",
        "water_level",
    ),
    "cz": (
        "cur_current",
        "cur_power",
        "cur_voltage",
        "add_ele",
        "pro_add_ele",
    ),
    "dghsxj": (
        "sensor_temperature",
        "sensor_humidity",
        "wireless_electricity",
    ),
    "dgnbj": (
        "gas_sensor_value",
        "ch4_sensor_value",
        "voc_value",
        "pm25_value",
        "co_value",
        "co2_value",
        "ec_current",
        "ch2o_value",
        "bright_state",
        "bright_value",
        "temp_current",
        "humidity_value",
        "orp_current",
        "ph_current",
        "smoke_sensor_value",
        "battery_percentage",
        "battery",
        "battery_state",
        "battery_value",
        "va_battery",
    ),
    "dlq": (
        "total_forward_energy",
        "add_ele",
        "forward_energy_total",
        "reverse_energy_total",
        "cur_neutral",
        "supply_frequency",
        ("phase_a", _CURRENT_WRAPPER),
        ("phase_a", _POWER_WRAPPER),
        ("phase_a", _VOLTAGE_WRAPPER),
        ("phase_b", _CURRENT_WRAPPER),
        ("phase_b", _POWER_WRAPPER),
        ("phase_b", _VOLTAGE_WRAPPER),
        ("phase_c", _CURRENT_WRAPPER),
        ("phase_c", _POWER_WRAPPER),
        ("phase_c", _VOLTAGE_WRAPPER),
        "cur_current",
        "cur_power",
        "cur_voltage",
    ),
    "fs": ("temp_current",),
    "ggq": (
        "battery_percentage",
        "battery",
        "battery_state",
        "battery_value",
        "va_battery",
    ),
    "hjjcy": (
        "air_quality_index",
        "temp_current",
        "humidity_value",
        "co2_value",
        "ch2o_value",
        "voc_value",
        "pm25_value",
        "pm10",
        "battery_percentage",
        "battery",
        "battery_state",
        "battery_value",
        "va_battery",
    ),
    "jqbj": (
        "co2_value",
        "voc_value",
        "pm25_value",
        "va_humidity",
        "va_temperature",
        "ch2o_value",
        "battery_percentage",
        "battery",
        "battery_state",
        "battery_value",
        "va_battery",
    ),
    "jsq": (
        "humidity_current",
        "temp_current",
        "temp_current_f",
        "level_current",
    ),
    "jwbj": (
        "ch4_sensor_value",
        "battery_percentage",
        "battery",
        "battery_state",
        "battery_value",
        "va_battery",
    ),
    "kg": (
        "cur_current",
        "cur_power",
        "cur_voltage",
        "add_ele",
        "pro_add_ele",
    ),
    "kj": (
        "filter",
        "pm25",
        "temp",
        "humidity",
        "tvoc",
        "eco2",
        "total_time",
        "total_pm",
        "air_quality",
    ),
    "ldcg": (
        "bright_state",
        "bright_value",
        "temp_current",
        "humidity_value",
        "co2_value",
        "battery_percentage",
        "battery",
        "battery_state",
        "battery_value",
        "va_battery",
    ),
    "mc": (
        "battery_percentage",
        "battery",
        "battery_state",
        "battery_value",
        "va_battery",
    ),
    "mcs": (
        "battery_percentage",
        "battery",
        "battery_state",
        "battery_value",
        "va_battery",
    ),
    "msp": (
        "cat_weight",
        "excretion_time_day",
        "excretion_times_day",
        "status",
    ),
    "mzj": (
        "temp_current",
        "status",
        "remain_time",
    ),
    "pc": (
        "cur_current",
        "cur_power",
        "cur_voltage",
        "add_ele",
        "pro_add_ele",
    ),
    "pir": (
        "battery_percentage",
        "battery",
        "battery_state",
        "battery_value",
        "va_battery",
    ),
    "pm2.5": (
        "pm25_value",
        "ch2o_value",
        "voc_value",
        "temp_current",
        "co2_value",
        "humidity_value",
        "pm1",
        "pm10",
        "battery_percentage",
        "battery",
        "battery_state",
        "battery_value",
        "va_battery",
    ),
    "qn": ("work_power",),
    "qxj": (
        "va_temperature",
        "temp_current",
        "temp_current_external",
        "temp_current_external_1",
        "temp_current_external_2",
        "temp_current_external_3",
        "va_humidity",
        "humidity_value",
        "humidity_outdoor",
        "humidity_outdoor_1",
        "humidity_outdoor_2",
        "humidity_outdoor_3",
        "atmospheric_pressture",
        "bright_value",
        "windspeed_avg",
        "rain_24h",
        "rain_rate",
        "uv_index",
        ("wind_direct", _WIND_DIRECTION_WRAPPER),
        "dew_point_temp",
        "feellike_temp",
        "heat_index",
        "windchill_index",
        "battery_percentage",
        "battery",
        "battery_state",
        "battery_value",
        "va_battery",
    ),
    "rqbj": (
        "gas_sensor_value",
        "battery_percentage",
        "battery",
        "battery_state",
        "battery_value",
        "va_battery",
    ),
    "sd": (
        "clean_area",
        "clean_time",
        "total_clean_area",
        "total_clean_time",
        "total_clean_count",
        "duster_cloth",
        "edge_brush",
        "filter",
        "roll_brush",
        "electricity_left",
    ),
    "sfkzq": (
        "time_use",
        "use_time_one",
        "work_state",
        "battery_percentage",
        "battery",
        "battery_state",
        "battery_value",
        "va_battery",
    ),
    "sgbj": (
        "battery_percentage",
        "battery",
        "battery_state",
        "battery_value",
        "va_battery",
    ),
    "sj": (
        "battery_percentage",
        "battery",
        "battery_state",
        "battery_value",
        "va_battery",
    ),
    "sos": (
        "battery_percentage",
        "battery",
        "battery_state",
        "battery_value",
        "va_battery",
    ),
    "sp": (
        "sensor_temperature",
        "sensor_humidity",
        "wireless_electricity",
    ),
    "swtz": (
        "temp_current",
        "temp_current_2",
        "battery_percentage",
        "battery",
        "battery_state",
        "battery_value",
        "va_battery",
    ),
    "sz": (
        "temp_current",
        "humidity_current",
    ),
    "szjcy": (
        "tds_in",
        "temp_current",
        "battery_percentage",
        "battery",
        "battery_state",
        "battery_value",
        "va_battery",
    ),
    "szjqr": (
        "battery_percentage",
        "battery",
        "battery_state",
        "battery_value",
        "va_battery",
    ),
    "tdq": (
        "cur_current",
        "cur_power",
        "cur_voltage",
        "add_ele",
        "va_temperature",
        "temp_current",
        "va_humidity",
        "humidity_value",
        "bright_value",
        "battery_percentage",
        "battery",
        "battery_state",
        "battery_value",
        "va_battery",
    ),
    "tyndj": (
        "battery_percentage",
        "battery",
        "battery_state",
        "battery_value",
        "va_battery",
    ),
    "voc": (
        "co2_value",
        "pm25_value",
        "ch2o_value",
        "humidity_value",
        "temp_current",
        "voc_value",
        "battery_percentage",
        "battery",
        "battery_state",
        "battery_value",
        "va_battery",
    ),
    "wg2": (
        "battery_percentage",
        "battery",
        "battery_state",
        "battery_value",
        "va_battery",
    ),
    "wk": (
        "battery_percentage",
        "battery",
        "battery_state",
        "battery_value",
        "va_battery",
    ),
    "wkcz": (
        "humidity_value",
        "temp_current",
        "cur_current",
        "cur_power",
        "cur_voltage",
    ),
    "wkf": (
        "battery_percentage",
        "battery",
        "battery_state",
        "battery_value",
        "va_battery",
    ),
    "wnykq": (
        "va_temperature",
        "va_humidity",
        "cur_current",
        "cur_power",
        "cur_voltage",
    ),
    "wsdcg": (
        "va_temperature",
        "temp_current",
        "va_humidity",
        "humidity_value",
        "bright_value",
        "battery_percentage",
        "battery",
        "battery_state",
        "battery_value",
        "va_battery",
    ),
    "wxkg": (
        "battery_percentage",
        "battery",
        "battery_state",
        "battery_value",
        "va_battery",
    ),
    "xnyjcn": (
        "current_soc",
        "pv_power_total",
        "pv_power_channel_1",
        "pv_power_channel_2",
        "battery_power",
        "inverter_output_power",
        "cumulative_energy_generated_pv",
        "cumulative_energy_output_inv",
        "cumulative_energy_discharged",
        "cumulative_energy_charged",
        "cuml_e_export_offgrid1",
    ),
    "ylcg": (
        "pressure_value",
        "battery_percentage",
        "battery",
        "battery_state",
        "battery_value",
        "va_battery",
    ),
    "ywbj": (
        "smoke_sensor_value",
        "battery_percentage",
        "battery",
        "battery_state",
        "battery_value",
        "va_battery",
    ),
    "ywcgq": (
        "liquid_state",
        "liquid_depth",
        "liquid_level_percent",
    ),
    "zd": (
        "battery_percentage",
        "battery",
        "battery_state",
        "battery_value",
        "va_battery",
    ),
    "zndb": (
        "forward_energy_total",
        "reverse_energy_total",
        "power_total",
        "total_power",
        "supply_frequency",
        ("phase_a", _CURRENT_WRAPPER),
        ("phase_a", _POWER_WRAPPER),
        ("phase_a", _VOLTAGE_WRAPPER),
        ("phase_b", _CURRENT_WRAPPER),
        ("phase_b", _POWER_WRAPPER),
        ("phase_b", _VOLTAGE_WRAPPER),
        ("phase_c", _CURRENT_WRAPPER),
        ("phase_c", _POWER_WRAPPER),
        ("phase_c", _VOLTAGE_WRAPPER),
    ),
    "znnbq": (
        "reverse_energy_total",
        "power_total",
        "temp_current",
    ),
    "znrb": (
        "compressor_strength",
        "temp_around",
        "temp_coiler",
        "temp_current",
        "temp_effluent",
        "temp_venting",
    ),
    "zwjcy": (
        "temp_current",
        "humidity",
        "battery_percentage",
        "battery",
        "battery_state",
        "battery_value",
        "va_battery",
    ),
}


def get_sensor_default_definitions(
    device: CustomerDevice,
) -> list[SensorDefinition]:
    """Get the default sensor definitions Home Assistant builds for a device."""
    values: list[SensorDefinition | None] = []
    for entry in _SENSOR_DPCODES.get(device.category, ()):
        if isinstance(entry, str):
            values.append(get_default_definition(device, entry))
        else:
            dpcode, wrapper_class = entry
            values.append(get_default_definition(device, dpcode, wrapper_class))
    return [definition for definition in values if definition]


def get_sensor_wrapper(
    definitions: list[SensorDefinition], dpcode: str
) -> DPCodeWrapper | None:
    """Extract the sensor wrapper for a DPCode from a list of definitions."""
    for definition in definitions:
        wrapper = definition.sensor_wrapper
        if isinstance(wrapper, DPCodeWrapper) and wrapper.dpcode == dpcode:
            return wrapper
    return None
